import { MunicipalWorker } from '../types';

export const ADMIN_EMAILS: string[] = [
  'narzo4643@gmail.com',
  'admin@binsync.gov',
  'admin@binsync.com',
  'officer.verma@binsync.gov.in',
];

export const INITIAL_WORKERS: MunicipalWorker[] = [
  {
    id: 'W-101',
    name: 'Rajesh Kumar',
    email: 'rajesh.worker@binsync.gov',
    gender: 'male',
    badge: 'W-101',
    unit: 'Unit 01 - North Ward',
    active: true,
    phone: '+91 98111 01001',
    zone: 'North Ward',
    status: 'Available',
    assignedTasks: 0,
    completedTasks: 0,
    rating: 4.8,
  },
  {
    id: 'W-102',
    name: 'Sunita Devi',
    email: 'sunita.worker@binsync.gov',
    gender: 'female',
    badge: 'W-102',
    unit: 'Unit 02 - Central Ward',
    active: true,
    phone: '+91 98111 01002',
    zone: 'Central Ward',
    status: 'Available',
    assignedTasks: 0,
    completedTasks: 0,
    rating: 4.9,
  },
  {
    id: 'W-103',
    name: 'Amit Verma',
    email: 'amit.worker@binsync.gov',
    gender: 'male',
    badge: 'W-103',
    unit: 'Unit 03 - South Ward',
    active: true,
    phone: '+91 98111 01003',
    zone: 'South Ward',
    status: 'Available',
    assignedTasks: 0,
    completedTasks: 0,
    rating: 4.7,
  },
  {
    id: 'W-104',
    name: 'Meena Kumari',
    email: 'meena.worker@binsync.gov',
    gender: 'female',
    badge: 'W-104',
    unit: 'Unit 04 - East Ward',
    active: true,
    phone: '+91 98111 01004',
    zone: 'East Ward',
    status: 'On Duty',
    assignedTasks: 1,
    completedTasks: 31,
    rating: 4.9,
  },
  {
    id: 'W-105',
    name: 'Vikram Singh',
    email: 'vikram.worker@binsync.gov',
    gender: 'male',
    badge: 'W-105',
    unit: 'Unit 05 - Rapid Clean Squad',
    active: true,
    phone: '+91 98111 01005',
    zone: 'Sector A',
    status: 'Available',
    assignedTasks: 0,
    completedTasks: 19,
    rating: 4.7,
  },
];

export const MUNICIPAL_AREAS: string[] = [
  'College Road',
  'Civil Lines',
  'Sector A',
  'Sector B',
  'Green Park',
  'University Area',
  'Market Zone',
  'Industrial Area',
];
